name: django-q2
channels:
  - conda-forge
  - pkgs/main
dependencies:
  - amqp=5.3.1=pyhd8ed1ab_0
  - asgiref=3.11.0=pyhcf101f3_1
  - backports.zstd=1.3.0=py312h44dc372_0
  - billiard=4.2.4=py312h4409184_0
  - blessed=1.29.0=pyh5552912_0
  - boto3=1.42.39=pyhd8ed1ab_0
  - botocore=1.42.39=pyhd8ed1ab_0
  - brotli-python=1.2.0=py312h0dfefe5_1
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - celery=5.5.3=pyhe01879c_0
  - click=8.3.1=pyh8f84b5b_1
  - click-didyoumean=0.3.1=pyhd8ed1ab_1
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - click-repl=0.3.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - django=6.0.1=pyhd8ed1ab_0
  - django-celery-results=2.5.1=pyh29332c3_2
  - django-picklefield=3.4.0=pyhd8ed1ab_0
  - django-q2=1.9.0=pyhcf101f3_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - iniconfig=2.3.0=pyhd8ed1ab_0
  - jmespath=1.1.0=pyhcf101f3_1
  - kombu=5.5.4=pyha770c72_0
  - libcxx=21.1.8=hf598326_1
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=he5f378a_0
  - liblzma=5.8.2=h8088a28_0
  - libsqlite=3.51.2=h1b79a29_0
  - libzlib=1.3.1=h8359307_2
  - ncurses=6.5=h5e97a16_3
  - openssl=3.6.1=hd24854e_1
  - packaging=26.0=pyhcf101f3_0
  - pip=26.0=pyh8b19718_0
  - pluggy=1.6.0=pyhf9edf01_1
  - prompt-toolkit=3.0.52=pyha770c72_0
  - prompt_toolkit=3.0.52=hd8ed1ab_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - pytest=9.0.2=pyhcf101f3_0
  - pytest-django=4.11.1=pyhd8ed1ab_0
  - python=3.12.12=h18782d2_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - readline=8.3=h46df422_0
  - redis=3.5.3=pyhd3eb1b0_0
  - s3transfer=0.16.0=pyhd8ed1ab_0
  - setuptools=80.10.2=pyh332efcf_0
  - six=1.17.0=pyhe01879c_1
  - sqlparse=0.5.5=pyhcf101f3_0
  - tk=8.6.13=h892fb3f_3
  - tomli=2.4.0=pyhcf101f3_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - urllib3=2.6.3=pyhd8ed1ab_0
  - vine=5.1.0=pyhd8ed1ab_1
  - wcwidth=0.5.3=pyhd8ed1ab_0
  - wheel=0.46.3=pyhd8ed1ab_0
  - zstd=1.5.7=hbf9d68e_6
  - pip:
    - django-celery==3.1.17

prefix: "/Users/georgii/.local/share/mamba/envs/django-q2"
